name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them'
runs: #this is fixed
  using: 'composite' #this is fixed
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash  # additional value for the custom aciton to know which shell to use